using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Xna.Framework;
using StardewModdingAPI;
using StardewModdingAPI.Events;
using StardewValley;
using StardewValley.GameData.Minecarts;
using StardewValley.ItemTypeDefinitions;
using StardewValley.Locations;
using StardewValley.TerrainFeatures;
using xTile;
using SObject = StardewValley.Object;

namespace OmniFarm
{
    public class OmniFarm : Mod
    {
        /*********
        ** Fields
        *********/
        private OmniFarmConfig Config;
        private MinecartDestinationData FarmDestination; // minecart destination

        /*********
        ** Public methods
        *********/
        /// <summary>The mod entry point, called after the mod is first loaded.</summary>
        /// <param name="helper">Provides simplified APIs for writing mods.</param>
        public override void Entry(IModHelper helper)
        {
            this.Config = helper.ReadConfig<OmniFarmConfig>();
            this.FarmDestination = CreateFarmDestination();

            helper.Events.Content.AssetRequested += OnAssetRequested;
            helper.Events.GameLoop.DayStarted += OnDayStarted;
        }

        /*********
        ** Private methods
        *********/
        /// <inheritdoc cref="IContentEvents.AssetRequested" />
        /// <param name="sender">The event sender.</param>
        /// <param name="e">The event arguments.</param>
        private void OnAssetRequested(object sender, AssetRequestedEventArgs e)
        {
            if (e.Name.IsEquivalentTo(@"Maps\Farm_Combat"))
                e.LoadFromModFile<xTile.Map>(@"assets\Farm_OmniFarm.tmx", AssetLoadPriority.Exclusive);
            if (e.Name.IsEquivalentTo(@"Maps\FarmCave") && Config.useOptionalCave)
                e.LoadFromModFile<xTile.Map>(@"assets\FarmCave_OmniFarm.tmx", AssetLoadPriority.Exclusive);
            if (e.Name.IsEquivalentTo(@"Data\Minecarts") && Config.addFarmMinecartDest)
                e.Edit(EditMinecartsData);
        }

        /// <inheritdoc cref="IGameLoopEvents.DayStarted"/>
        /// <param name="sender">The event sender.</param>
        /// <param name="e">The event data.</param>
        private void OnDayStarted(object sender, EventArgs e)
        {
            
            if (Game1.whichFarm == Farm.combat_layout)
            {
                ChangeWarpPoints();

                foreach (GameLocation GL in Game1.locations)
                {
                    if (GL is Farm ourFarm)
                    {
                        // stumps now generated by map properties

                        foreach (Vector2 tile in Config.hollowLogLocations)
                        {
                            ClearResourceClump(ourFarm.resourceClumps, tile);
                            ourFarm.addResourceClumpAndRemoveUnderlyingTerrain(ResourceClump.hollowLogIndex, 2, 2, tile);
                        }

                        foreach (Vector2 tile in Config.meteoriteLocations)
                        {
                            ClearResourceClump(ourFarm.resourceClumps, tile);
                            ourFarm.addResourceClumpAndRemoveUnderlyingTerrain(ResourceClump.meteoriteIndex, 2, 2, tile);
                        }

                        foreach (Vector2 tile in Config.boulderLocations)
                        {
                            ClearResourceClump(ourFarm.resourceClumps, tile);
                            ourFarm.addResourceClumpAndRemoveUnderlyingTerrain(ResourceClump.boulderIndex, 2, 2, tile);
                        }

                        foreach (Vector2 tile in Config.largeRockLocations)
                        {
                            ClearResourceClump(ourFarm.resourceClumps, tile);
                            ourFarm.addResourceClumpAndRemoveUnderlyingTerrain(ResourceClump.mineRock1Index, 2, 2, tile);
                        }

                        //grass
                        if (Game1.IsWinter == false)
                            foreach (Vector2 tile in Config.GetGrassLocations())
                            {
                                if (ourFarm.terrainFeatures.TryGetValue(tile, out TerrainFeature check))
                                {
                                    if (check is Grass grass)
                                        grass.numberOfWeeds.Value = Config.GrassGrowth_1forsparse_4forFull;
                                }
                                else
                                    ourFarm.terrainFeatures.Add(tile, new Grass(Grass.springGrass, Config.GrassGrowth_1forsparse_4forFull));
                            }

                        //mine
                        Random randomGen = new Random();
                        foreach (Vector2 tile in Config.GetMineLocations())
                        {
                            if (ourFarm.isObjectAt((int)tile.X, (int)tile.Y))
                                continue;

                            //calculate ore spawn
                            if (Game1.player.hasSkullKey)
                            {
                                //5% chance of spawn ore
                                if (randomGen.NextDouble() < Config.oreChance)
                                {
                                    AddRandomOre(ref ourFarm, ref randomGen, 4, tile);
                                    continue;
                                }
                            }
                            else
                            {
                                //check mine level
                                if (Game1.player.deepestMineLevel > 80) //gold level
                                {
                                    if (randomGen.NextDouble() < Config.oreChance)
                                    {
                                        AddRandomOre(ref ourFarm, ref randomGen, 3, tile);
                                        continue;
                                    }
                                }
                                else if (Game1.player.deepestMineLevel > 40) //iron level
                                {
                                    if (randomGen.NextDouble() < Config.oreChance)
                                    {
                                        AddRandomOre(ref ourFarm, ref randomGen, 2, tile);
                                        continue;
                                    }
                                }
                                else
                                {
                                    if (randomGen.NextDouble() < Config.oreChance)
                                    {
                                        AddRandomOre(ref ourFarm, ref randomGen, 1, tile);
                                        continue;
                                    }
                                }
                            }

                            //if ore doesn't spawn then calculate gem spawn
                            //1% to spawn gem
                            if (randomGen.NextDouble() < Config.gemChance)
                            {
                                //0.1% chance of getting mystic stone
                                if (Game1.player.hasSkullKey)
                                    if (randomGen.Next(0, 100) < 1)
                                    {
                                        ourFarm.setObject(tile, CreateOre("mysticStone", tile));
                                        continue;
                                    }
                                    else
                                    if (randomGen.Next(0, 500) < 1)
                                    {
                                        ourFarm.setObject(tile, CreateOre("mysticStone", tile));
                                        continue;
                                    }

                                switch (randomGen.Next(0, 100) % 8)
                                {
                                    case 0: ourFarm.setObject(tile, CreateOre("gemStone", tile)); break;
                                    case 1: ourFarm.setObject(tile, CreateOre("diamond", tile)); break;
                                    case 2: ourFarm.setObject(tile, CreateOre("ruby", tile)); break;
                                    case 3: ourFarm.setObject(tile, CreateOre("jade", tile)); break;
                                    case 4: ourFarm.setObject(tile, CreateOre("amethyst", tile)); break;
                                    case 5: ourFarm.setObject(tile, CreateOre("topaz", tile)); break;
                                    case 6: ourFarm.setObject(tile, CreateOre("emerald", tile)); break;
                                    case 7: ourFarm.setObject(tile, CreateOre("aquamarine", tile)); break;
                                }
                                continue;
                            }
                        }
                    }
                }
            }
        }

        /// <summary>Constructs the Farm's minecart destination data.</summary>
        /// <returns>The minecart destination entry for the Farm.</returns>
        private static MinecartDestinationData CreateFarmDestination()
        {
            var farm_loc = new MinecartDestinationData();

            farm_loc.Id = "OmniFarm.Farm";
            farm_loc.DisplayName = "Farm";
            farm_loc.Condition = null;
            farm_loc.Price = 0;
            farm_loc.BuyTicketMessage = null;
            farm_loc.TargetLocation = "Farm";
            farm_loc.TargetTile.X = 77;
            farm_loc.TargetTile.Y = 7;
            farm_loc.TargetDirection = null;
            farm_loc.CustomFields = null;

            return farm_loc;
        }

        /// <summary>Adds the Farm as a destination on for the Minecart network.</summary>
        /// <param name="asset">The minecart network asset.</param>
        private void EditMinecartsData(IAssetData asset)
        {
            // Don't edit the data if on a different farm type
            if (Game1.whichFarm != Farm.combat_layout)
                return;

            var destinations = asset.AsDictionary<string, MinecartNetworkData>().Data["Default"].Destinations;
            destinations.Add(this.FarmDestination);
        }

        /// <summary>Updates the farm's entry warp points to the proper coordinates, if specified.</summary>
        private void ChangeWarpPoints()
        {
            // NOTE: The TMX version of the map now includes the entry warps in the map properties,
            // so most of the time this won't be needed (kept for compatibility)
            foreach (GameLocation GL in Game1.locations)
            {
                if (Config.WarpFromForest.X != -1)
                {
                    if (GL is Forest)
                    {
                        foreach (Warp w in GL.warps)
                        {
                            if (w.TargetName.ToLower().Contains("farm"))
                            {
                                w.TargetX = (int)Config.WarpFromForest.X;
                                w.TargetY = (int)Config.WarpFromForest.Y;
                            }
                        }
                    }
                }

                if (Config.WarpFromBackWood.X != -1)
                {
                    if (GL.Name.ToLower().Contains("backwood"))
                    {
                        foreach (Warp w in GL.warps)
                        {
                            if (w.TargetName.ToLower().Contains("farm"))
                            {
                                w.TargetX = (int)Config.WarpFromBackWood.X;
                                w.TargetY = (int)Config.WarpFromBackWood.Y;
                            }
                        }
                    }
                }

                if (Config.WarpFromBusStop.X != -1)
                {     
                    if (GL.Name.ToLower().Contains("busstop"))
                    {
                        foreach (Warp w in GL.warps)
                        {
                            if (w.TargetName.ToLower().Contains("farm"))
                            {
                                w.TargetX = (int)Config.WarpFromBusStop.X;
                                w.TargetY = (int)Config.WarpFromBusStop.Y;
                            }
                        }
                    }
                }
            }
        }

        private static void AddRandomOre(ref Farm input, ref Random randomGen, int highestOreLevel, Vector2 tileLocation)
        {
            switch (randomGen.Next(0, 100) % highestOreLevel)
            {
                case 0: input.setObject(tileLocation, CreateOre("copperStone", tileLocation)); break;
                case 1: input.setObject(tileLocation, CreateOre("ironStone", tileLocation)); break;
                case 2: input.setObject(tileLocation, CreateOre("goldStone", tileLocation)); break;
                case 3: input.setObject(tileLocation, CreateOre("iridiumStone", tileLocation)); break;
            }
        }

        private static ItemMetadata GetItemMetadata(string id)
        {
            return ItemRegistry.GetMetadata(id);
        }

        private static SObject GetObjectByID(int id)
        {
            string objStr = "(O)" + id;
            return (SObject)GetItemMetadata(objStr).CreateItemOrErrorItem();
        }

        private static SObject CreateOre(string oreName, Vector2 tileLocation)
        {
            switch (oreName)
            {
                case "mysticStone": return GetObjectByID(46);
                case "gemStone": return GetObjectByID((Game1.random.Next(7) + 1) * 2);
                case "diamond": return GetObjectByID(2);
                case "ruby": return GetObjectByID(4);
                case "jade": return GetObjectByID(6);
                case "amethyst": return GetObjectByID(8);
                case "topaz": return GetObjectByID(10);
                case "emerald": return GetObjectByID(12);
                case "aquamarine": return GetObjectByID(14);
                case "iridiumStone": return GetObjectByID(765);
                case "goldStone": return GetObjectByID(764);
                case "ironStone": return GetObjectByID(290);
                case "copperStone": return GetObjectByID(751);
                default: return null;
            }
        }

        private static void ClearResourceClump(IList<ResourceClump> input, Vector2 tile)
        {
            for (int i = 0; i < input.Count; i++)
            {
                ResourceClump RC = input[i];
                if (RC.Tile == tile)
                {
                    input.RemoveAt(i);
                    i--;
                }
            }
        }
    }
}
